name: CI

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: dotnet build -c Release

    - name: Run tests
      run: dotnet test -c Release --no-build

  run:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: dotnet build -c Release

    - name: Run
      run: dotnet run -c Release --no-build
      working-directory: ./src/AoC_2020

#  benchmark:
#    runs-on: ${{ matrix.os }}
#
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest, macOS-latest]
#      fail-fast: false
#
#    env:
#      DOTNET_CLI_TELEMETRY_OPTOUT: 1
#
#    steps:
#    - uses: actions/checkout@v2.3.4
#
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1.7.2
#      with:
#        dotnet-version: 5.0.x
#
#    - name: Build
#      run: dotnet build -c Release
#
#    - name: Run All_Days_Benchmark
#      run: dotnet run -c Release --no-build --filter All_Days_Benchmark
#      working-directory: ./src/AoC_2020.Benchmarks
#
#    - name: 'Upload ${{ matrix.os }} artifacts'
#      continue-on-error: true
#      uses: actions/upload-artifact@v2
#      with:
#        name: artifacts-${{ matrix.os }}-${{ github.run_number }}
#        path: ./src/AoC_2020.Benchmarks/BenchmarkDotNet.Artifacts/results/
#        if-no-files-found: error
